#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState
from geometry_msgs.msg import Point
import math

class ForwardKinematicsNode(Node):
    def __init__(self):
        super().__init__('forward_kinematics_node')

        self.L1 = 2.0
        self.L2 = 1.5

        self.subscription = self.create_subscription(
            JointState,
            '/joint_states',
            self.joint_state_callback,
            10
        )

        self.publisher = self.create_publisher(
            Point,
            '/end_effector_position',
            10
        )

        self.get_logger().info('Forward Kinematics Node started.')

    def joint_state_callback(self, msg):
        if len(msg.position) < 3:
            self.get_logger().warn("Expected at least 3 joint values.")
            return

        theta1 = msg.position[1] + math.pi / 2.0  # shoulder_pitch_joint
        theta2 = msg.position[2]                 # elbow_joint

        x = self.L1 * math.cos(theta1) + self.L2 * math.cos(theta1 + theta2)
        y = self.L1 * math.sin(theta1) + self.L2 * math.sin(theta1 + theta2)

        point = Point()
        point.x = x
        point.y = y
        point.z = 0.0

        self.publisher.publish(point)
        self.get_logger().info(f"Published EE Position: x={x:.2f}, y={y:.2f}")



def main(args=None):
    rclpy.init(args=args)
    node = ForwardKinematicsNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
